### PR TITLE
Bitfinex only

### PR DESCRIPTION
**Pull request by nedievas**
I'm testing this bot on Bitfinex. Now it's gathering historical data.

### CODE REVIEW

**Comment by eigilb** [comment]
The run.sh script doesn't seem to  start sim. Can "./zenbot sim" be started separately without stop the already running zenbot? It isn't clear from the docs. 
At the moment I am also looking at gekko. Which one has, in your opinion, the best potential?
Thanks.

**Comment by nedievas** [comment]
run.sh is to launch paper/real trading bot. You may launch simulation separately via ./zenbot sim --verbose (for default config) or ./zenbot sim --verbose --config config_dsh_usd.js (for different pairs, assuming you have backfilled that pair prior simulation).  You do not have to stop trading.
I have gekko in the background, but for this moment it has poorer profitability for BTCUSD than zenbot. I had tested different strategies on gekko vs the only strategy in zenbot:) I will observe further.

**Comment by nedievas** [comment]
run.sh is to launch paper/real trading bot. 
You may launch simulation separately via ./zenbot sim --verbose (for default config) or ./zenbot sim --verbose --config config_dsh_usd.js (for different pairs, assuming you have backfilled that pair prior simulation).  You do not have to stop trading.
I have gekko in the background, but for this moment it has poorer profitability for BTCUSD than zenbot. I had tested different strategies on gekko vs the only strategy in zenbot:) I will observe further.

**Comment by eigilb** [comment]
This one doesn't show much promise. It is from running the Stratrunner. 
Running backtesting with the same parameters showed some 17% plus. That 
makes me suspicious.

<https://cloud.githubusercontent.com/assets/26491085/24610990/f0e1153c-1880-11e7-80ad-ba76d11007d3.jpg>

If you want to exchange ideas that doesn't fit into github issues, you 
can PM me to tuxador (at) tux (dot) no.

Over time I might be able to make some contributions.


Den 03. april 2017 16:15, skrev nedievas:

**Pull request merged**
